### ISSUE TITLE
License not found

### ISSUE THREAD

**Issue by monoid** [yandex-tabkit/tabkit#2]
It is not clear if I can use and modify the code.  It is not even clear if I can read it.

**Comment by monoid** [comment]
There is https://github.com/yandex-tabkit/tabkit/blob/master/debian/copyright#L20
but it is not clear if it defines license for whole package.

**Comment by subdir** [comment]
:-P

**Comment by monoid** [comment]
We decided in private talk with @subdir to use a MIT license.

**Comment by monoid** [comment]
856eeed9dc925d9a69471c4ca274f2e57046e7c1
